### ISSUE TITLE
PaymentRequest prefix matching shouldn't use tryExactlyOne

### ISSUE THREAD

**Issue by ysangkok** [joemphilips/DotNetLightning#104]
Since lnbc is a prefix of lnbcrt, two prefixes may match. The longest should be tried first, but the current behaviour is to fail when multiple matches are found, which will be the case when a regtest invoice is parsed.

**Comment by ysangkok** [comment]
The first matching value of prefixValues could be used, but only if it was guaranteed to have the longest values first, which is not guaranteed, since it is constructed from a Map.

**Comment by joemphilips** [comment]
Thanks for reporting, fixed in bffe69c9f2e7e64c586752a05fc38eed8dbbada5
