### ISSUE TITLE
Stop relying on myget.org/F/joemphilips/ feed

### ISSUE THREAD

**Issue by knocte** [joemphilips/DotNetLightning#12]
For full _open-sourcey_ transparency, cannot we publish `Secp256k1.Native` in nuget.org too?

**Comment by joemphilips** [comment]
OK. But let me finish Routing and whole integration tests first.

**Comment by joemphilips** [comment]
fix in #44

**Comment by knocte** [comment]
> OK. But let me finish Routing and whole integration tests first.

Does this mean that Routing is finished? :)

**Comment by joemphilips** [comment]
No... there is still a lot more to work on.  🤣

**Comment by knocte** [comment]
Hehehe.
