### ISSUE TITLE
DotNetLightning conflates RevocationKey and PerCommitmentSecret

### ISSUE THREAD

**Issue by canndrew** [joemphilips/DotNetLightning#130]
When trying to use DotNetLightning to implement revocation in geewallet I struggled to make sense of the revocation APIs until I realized they don't actually make sense. The main problem is that revocation keys and per commitment secrets are two different things, yet the `RevocationKey` type is actually a type that holds a per commitment secret. This is my doing, since I added the `RevocationKey`/`RevocationSet` types. Additionally, some key-related fields and variables have names that don't match the names in the lightning spec. This made it difficult for me to be confident that I'm using keys correctly, especially after I became aware that at least one thing I had to use was completely misnamed as another thing.

To fix this I'm working on a PR that (a) renames `Revocation{Key,Set}` as well as some fields to match the names used in the spec and (b) adds `Key`/`PubKey`-wrapper types for some more keys (like I did for `RevocationKey`) so that it's a type-error to use them incorrectly (eg. by using the wrong key to derive some other key). This should make both DNL's and its consumers' code more readable as well as more bug-proof.

The WIP branch is here: https://github.com/canndrew/DotNetLightning/tree/key-types-refactor

**Comment by joemphilips** [comment]
Sorry this is my bad. I first ported everything from rust-lightning/eclair without understanding what actually it is.
