### ISSUE TITLE
Channel closing fails with "failed to finalize psbt"

### ISSUE THREAD

**Issue by canndrew** [joemphilips/DotNetLightning#131]
## Steps to reproduce:

0. (In geewallet we have a test that does this):
1. opens a channel against another geewallet
2. closes the channel (using DotNetLightning)

## Current results:

About 50% of the time the peer which accepts the channel close (not the initiator) will crash with an exception thrown from DotNetLightning:

```
TransactionRelatedErrors
        [FailedToFinalizeScript
           "failed to finalize psbt Errors: seq [Input 0: The finalized input script does not properly validate "NullFail"] 
 PSBTInput: {
  "index": 0,
  "partial_signatures": {
    "02db5e2701d93ca1b07c851dda2125d4b6cc36fe378db3719f384ba7dd2dfa2d8c": "304402206b74ee87e5955097515c9c300b01a9b4f7762ac102915291add469cb3dcf256c022073457a0a6f931a0ff29e9fbf29972d3a2d9b2147946b09839cf5a3ecd018dfb701",
    "0389ecd0689e9db416e2a04eda4cc817aae00bb906765f29616617ec10120039cd": "304402205e3c21be6cd331a590662d8161c521e0e82440f0981959cc7f5a43b72e2c2c5d022040de0b8d750178fbc81b339368a287142b7e0789971f0df0b1e659c71f74a22101"
  },
  "witness_script": "2 02db5e2701d93ca1b07c851dda2125d4b6cc36fe378db3719f384ba7dd2dfa2d8c 0389ecd0689e9db416e2a04eda4cc817aae00bb906765f29616617ec10120039cd 2 OP_CHECKMULTISIG",
  "witness_utxo": {
    "value": "0.10000000",
    "scriptPubKey": "0 97548049d3dea0202df8566d01fcd747b1157b9c4bd5b49aa07e1f49a4883ba5"
  },
  "bip32_derivs": []
} 
 base64 PSBT: cHNidP8BAHMCAAAAAfvA05Q3DdmVyZAlCpXMh97XuFJkSt2PY1zRQsiqWK9bAAAAAAD/////AqAlJgAAAAAAF6kUaE6LBCrgQ3qWZuXvaVhWIIN5cT6HrE9yAAAAAAAXqRT1S8cHNnV67ocL/6lFxS02Vp64CIcAAAAAAAEBK4CWmAAAAAAAIgAgl1SASdPeoCAt+FZtAfzXR7EVe5xL1bSaoH4fSaSIO6UBBUdSIQLbXicB2TyhsHyFHdohJdS2zDb+N42zcZ84S6fdLfotjCEDiezQaJ6dtBbioE7aTMgXquALuQZ2XylhZhfsEBIAOc1SriICAtteJwHZPKGwfIUd2iEl1LbMNv43jbNxnzhLp90t+i2MRzBEAiBrdO6H5ZVQl1FcnDALAam093YqwQKRUpGt1GnLPc8lbAIgc0V6Cm+TGg/ynp+/KZctOi2bIUeUawmDnPWj7NAY37cBIgIDiezQaJ6dtBbioE7aTMgXquALuQZ2XylhZhfsEBIAOc1HMEQCIF48Ib5s0zGlkGYtgWHFIeDoJEDwmBlZzH9aQ7cuLCxdAiBA3guNdQF4+8gbM5NooocUK34HiZcfDfCx5lnHH3SiIQEAAAA="]
 ```

## Expected results (which actually happens 50% of the times):

Doesn't crash and closes the channel.

**Comment by canndrew** [comment]
Any idea what's causing this? It's coming from `PSBT.TryFinalize` in `NBitcoin`. As far as I can see, the only relevant place where `NBitcoin` throws a `NullFail` is when checking the transaction signatures when checking an `OP_CHECKMULTISIG`, so perhaps the transaction is malformed relative to the signatures? As I say, this only happens about 50% of the time though, (and works the rest of the time) so maybe that's a clue.

**Comment by knocte** [comment]
@joemphilips FYI, Andrew has tried your PR nr. 121 and it doesn't help :(

**Comment by knocte** [comment]
> closes the channel (using DotNetLightning)

@canndrew just to be clear, who initiates the closing? the funder or the fundee?

**Comment by canndrew** [comment]
The funder initiates the closing. When it fails it always fails on the fundee's side.

**Comment by knocte** [comment]
Ok thanks! Joe wrote NBitcoin's PSBT implementation so hopefully he can give us some hints of how to debug this :)

**Comment by canndrew** [comment]
The problem is something to do with fee negotiation. When it breaks, the fee rates are different on the two sides of the channel...

**Comment by knocte** [comment]
Do we send any update_fee messages in geewallet? If yes, can we avoid them for this test, to check if it fixes the problem for now?

**Comment by joemphilips** [comment]
I will take a close look tomorrow. nullfail often means that an order of pubkeys and an order of signatures are different.

**Comment by knocte** [comment]
> order of pubkeys and an order of signatures...

Order huh? I don't know why, this reminds me of an old conversation we had about shuffling inputs/outputs in NBitcoin.

And I think NBitcoin supports this weird behaviour thanks to the merging of this PR: https://github.com/MetacoSA/NBitcoin/commit/db0d8247d372c2aa5b23017c038618ddbf765241

Maybe DNL should use this feature?

**Comment by knocte** [comment]
(edited my comment above to make it clearer)

**Comment by joemphilips** [comment]
NullFail means signature verification is failing, so it should be a difference between the Closing Tx used for signing(on the funder side) and for verification (on the fundee side) So if I were you I would try printing the PSBT returned from `makeClosingTx` on both sides and see the difference.

**Comment by canndrew** [comment]
> So if I were you I would try printing the PSBT returned from makeClosingTx on both sides and see the difference.

That's what I did. The fee rates specified in the two PSBTs are different.

**Comment by canndrew** [comment]
I swear last week I was seeing a problem with fee rates being different on each end, but the error I'm getting now is that tx outputs are in different order on each end. There's no way to disable shuffling on a `TransactionBuilder` without upgrading to an `NBitcoin` that has the changes that @knocte linked above, and even then the lightning spec requires that the outputs are in lexicographic order but `TransactionBuilder` doesn't have a way to set this or to add the `TxOuts` manually (after comparing them to determine their order). So I'm going to avoid using `TransactionBuilder` in the fix. I already had to do this in other places in geewallet, and it doesn't seem like `TransactionBuilder` is actually buying us anything here.

**Comment by knocte** [comment]
Sorry, avoiding to use TransactionBuilder is a can of worms; been there, done that (using the more raw types from NBitcoin gives a lot of problems). Let's open a PR in NBitcoin to improve TransactionBuilder instead.

**Comment by joemphilips** [comment]
> I swear last week I was seeing a problem with fee rates being different on each end, but the error I'm getting now is that tx outputs are in different order on each end. 

It is possible that we have two problems here that both has to be fixed. :( 
I will take it if you make a PR that avoid using `TransationBuilder` altogether. That is other LN implementations do anyway (if I remember correctly). @canndrew 

It is true that avoiding using TransactionBuilder is a hard way to go as @knocte says, but I don't think it is impossible.

 Sidenote: I think what we really want here is another type of ` TransactionBuilder`, [that is what Nicolas doing in NDLC](https://github.com/dgarage/NDLC/blob/master/NDLC/DLCTransactionBuilder.cs) 
I once dreamed of something cool with Computation Expression (Thus F# specific), but I don't have enough time to ponder upon the detailed design.

**Comment by knocte** [comment]
> but I don't think it is impossible.

Nothing is impossible, we're just moving 1s and 0s around...

My point is that the possible bad consequences of not using TransactionBuilder might be too great, at least from the point of view of geewallet, because I've had nightmares in the past, to just name one example, when I was using raw Transaction types in geewallet to estimate fees. We need to be able to present realistic fee estimation in geewallet when the user wants to open and close channels, and the only reliable way to that today, without a much bigger time investment, is by using TransactionBuilder.

**Comment by joemphilips** [comment]
Yeah, I get your point.
