### ISSUE TITLE
CI issues

### ISSUE THREAD

**Issue by knocte** [joemphilips/DotNetLightning#153]
I've seen a couple of issues lately with CI:
* Some lanes fail randomly, e.g.: the one for this recent commit: https://github.com/joemphilips/DotNetLightning/commit/4812785e7971b81cb763ba0d94a5de804854da73
* In our fork where we test several things, we have noticed that the push to nuget.org can happen even if the other CI lanes didn't pass, which is wrong.

**Comment by joemphilips** [comment]
Let me investigate

**Comment by joemphilips** [comment]
The CI failure itself is caused only in "windows && non-bouncycastle" build in Macaroons.
I remember I had similar issue once before.
I can just stop supporting Macaroons in case of non-bouncycastle build (Or maybe I should stop supporting NSec all together).

But before that I want to support .NET 5 and future versions, so please give me some time to research what is the best way to do so.

I'm pretty sure that this issue does not affect you as long as you are using bouncycastle build. So you can ignore it for now.

**Comment by knocte** [comment]
> this issue does not affect you 

Yeah it doesn't matter for us technically, but it's noise when CI fails for reasons outside our control and the workaround is to just re-run CI.

> But before that I want to support .NET 5 and future versions, so please give me some time to research what is the best way to do so.

Sure, but DNL is a library, it doesn't have any executables. Therefore it can stay in .NETStandard form and .NET5 programs can use it just fine.

> In our fork where we test several things, we have noticed that the push to nuget.org can happen even if the other CI lanes didn't pass, which is wrong.

And how about this?

**Comment by knocte** [comment]
> I can just stop supporting Macaroons in case of non-bouncycastle build

How about just run Macaroon tests in BC build? and don't include it in the nuget package for the nonBC build

**Comment by joemphilips** [comment]
Hotfix merged in https://github.com/joemphilips/DotNetLightning/pull/155

In the future probably I must consider either
1. Stop supporting NSec build or
2. Fixed the test-failure issue on the windows.
