### ISSUE TITLE
Genesis hash not re-reversed

### ISSUE THREAD

**Issue by ysangkok** [joemphilips/DotNetLightning#18]
This error is reported by lnd when trying to open a channel to it from DotNetLightning:

`2019-10-08 22:56:10.103 [DBG] FNDG: Sending funding error to peer (031d86bc78a6d350059044168a50be4c3bda71b7a86d015a9ce253a2f419f445b4): (*lnwire.Error)(0xc00083c300)(chan_id=5555555555555555555555555555555555555555555555555555555555555555, err=Unknown chain=06226e46111a0b59caaf126043eb5bbf28c34f3a5e332a1fc7b2b73cf188910f. Supported chain=0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206)
`

Here is my temporary patch. It doesn't handle incoming channel requests, so not sending a PR for this. I can work on it if you'd like. but I figured it'll be easier to just let you patch it.

Channel.fs:

```
diff --git a/src/DotNetLightning.Core/LN/Channel.fs b/src/DotNetLightning.Core/LN/Channel.fs
index e271652..2b91f1f 100644
--- a/src/DotNetLightning.Core/LN/Channel.fs
+++ b/src/DotNetLightning.Core/LN/Channel.fs
@@ -533,8 +533,11 @@ module Channel =
 
         // --------------- open channel procedure: case we are funder -------------
         | WaitForInitInternal, CreateOutbound inputInitFunder ->
+            let revGenesis = cs.Network.Consensus.HashGenesisBlock.ToBytes()
+            Array.Reverse revGenesis
+            let revGenesisUint = uint256 revGenesis
             let openChannelMsgToSend = {
-                OpenChannel.Chainhash = cs.Network.Consensus.HashGenesisBlock
+                OpenChannel.Chainhash = revGenesisUint
                 TemporaryChannelId = inputInitFunder.TemporaryChannelId
                 FundingSatoshis = inputInitFunder.FundingSatoshis
                 PushMSat = inputInitFunder.PushMSat
```

**Comment by knocte** [comment]
@joemphilips ping

**Comment by joemphilips** [comment]
Sorry for the delay. fixed in 
e0c132ea04e74296af9b483a698c987bea57ee03

I'd better prepare integration test against other LN node at some point.

**Comment by knocte** [comment]
We can close this then? BTW I think it's better to use Seq.rev instead of Array.rev, the former is more generic (in case the underlying enumerator is changed from array to list, then seq.rev would still work on it).
