### ISSUE TITLE
Nuget package for DotNetLightning.ClnRpc has missing dependencies

### ISSUE THREAD

**Issue by rsafier** [joemphilips/DotNetLightning#224]
Missing two packages which are not public on Nuget so cannot try sample plugin code:
![image](https://user-images.githubusercontent.com/645964/184528221-89b32b35-049a-43e5-bce6-9a6e2fa707bf.png)

**Comment by knocte** [comment]
Hello @rsafier , thanks for reporting this problem!

I believe we have hit this problem before with the DotNetLightning nuget package, and we fixed it this way: https://github.com/joemphilips/DotNetLightning/commit/c98307465f647257df1438beadb4cabc7db757f2 .

So I guess we now need the same workaround for the DotNetLightning.ClnRpc project. Can you create a PR for this?

**Comment by joemphilips** [comment]
@rsafier 
You are referencing old version of `DotNetLightning.ClnRpc` The newest version is defined by prefix version number. (in the same way with [`System.Commandline` beta version](https://github.com/dotnet/command-line-api/tags) management.)

This is the newest.
https://www.nuget.org/packages/DotNetLightning.ClnRpc/1.1.2-date20220806-0225-git-7c5fdbb

@knocte I believe it is a different problem. the latest version has no dependency for ResultUtils and PluginLogger

Recently I received a similar feedback from others, it seems that managing a package version with VersionPrefix is not user-friendly.
I must consider defining a publication flow with semantic versioning... probably with the way similar to NBitcoin.

**Comment by knocte** [comment]
I guess it wasn't really @rsafier's fault because the version of the nuget package that fixed this issue was a pre-release. But I see that you just published a stable version (1.1.6) that contains the fix, so I guess we can close this now.

**Comment by joemphilips** [comment]
Yeah, I guess I will create a new release manually every time there is a change so that this kind of confusion won't happen again.

At some point I should introduce more sophisticated/automated flow.
