### ISSUE TITLE
TODO: Make integration of Secp256k1.Native more secure.

### ISSUE THREAD

**Issue by joemphilips** [joemphilips/DotNetLightning#56]
Currently, when we build with no `BouncyCastle=true` flag, we use native bindings for `libsecp256k1`  (which I have forked to [this repo](https://github.com/joemphilips/secp256k1))

To make it more secure, we should either

1. incorporate the repository into this repo.
2. stop using my own fork when libsecp256k1 supports deterministic build and stable API versioning (Which seems to be tracked by following issues)
  * https://github.com/bitcoin-core/secp256k1/issues/255
  * https://github.com/bitcoin-core/secp256k1/issues/286

**Comment by knocte** [comment]
We using now NBitcoin's secp256k1 right?, so this issue is obsolete and can be closed?

**Comment by joemphilips** [comment]
Yep.
