### ISSUE TITLE
TODO: Code Formatting

### ISSUE THREAD

**Issue by joemphilips** [joemphilips/DotNetLightning#58]
Right now we don't have any automated code formatting scheme.
It is nice to have formatting pipeline in CI.

**Comment by knocte** [comment]
Via fantomas?

**Comment by joemphilips** [comment]
@knocte probably, I don't know what is the state of the art.

**Comment by knocte** [comment]
I think fantomas is the state of the art, if not the only option. But I wouldn't make use of it at least until this PR is merged: https://github.com/fsprojects/fantomas/pull/649 otherwise the inconsistency between having a space before parenthesis or not becomes too annoying.

**Comment by joemphilips** [comment]
Thanks for the info. I think it still has some benefits without that feature, but there is no hurry.

**Comment by knocte** [comment]
I don't know, to me, having different spacing style depending on if the function called/defined starts with an uppercase letter or not, is master-level of bikeshedding.
