### ISSUE TITLE
TODO: fail on focused tests in CI

### ISSUE THREAD

**Issue by joemphilips** [joemphilips/DotNetLightning#59]
Expecto has a cli argument called `--fail-on-focused-tests` 
This should be turned on in CI. But It might be not straightforward for following reasons.
1. tests are run by `dotnet test` not by `dotnet run` (which is a recommended way to run Expecto)
2. `DotNetLightning.Integration.Tests` is planned to run by xunit, since it works well than Expecto for Asp.Net core (e.g. when using `WebApplicatoinFactory` )

**Comment by knocte** [comment]
What are "focused tests" exactly?

**Comment by joemphilips** [comment]
> What are "focused tests" exactly?

`ftestCase` , `ftestPropetyWithConfig` . etc

**Comment by knocte** [comment]
Not sure I get what you're saying. They are just "focused tests" because they start with "f"? And what does it mean that a test is "focused"?

**Comment by joemphilips** [comment]
https://github.com/haf/expecto#focusing-tests

When there is one `ftestCase` in the code, all other tests won't run.
Thus it can easily pass the CI without running other tests.

This can happen because `ftestCase` is useful when debugging.

**Comment by joemphilips** [comment]
Addressed in https://github.com/joemphilips/DotNetLightning/pull/191
