### ISSUE TITLE
Consider binding to rust-lightning.

### ISSUE THREAD

**Issue by joemphilips** [joemphilips/DotNetLightning#74]
Recently, rust-lightning got sponsored by square crypto and it is likely to be maintained in a long term as Lightning Developer Kit.
If we are able to create a binding against rust-lightning, DotNetLightning.Core can be a thin wrapper around it and we don't have to care about nitty-gritty part like channel state management or so.

**Comment by joemphilips** [comment]
@knocte taught me about @canndrew 's previous [attempt to create the bindings against rust-lightning](https://gitlab.com/nblockchain/geelightning),.
See [his comments here](https://gitlab.com/nblockchain/geewallet/-/merge_requests/72#note_279998877)

 @canndrew seems to understand about FFI much better than me, and the fact that even he decided not to go on that path made me hesitant to trying it by myself.


I may come back to this issue later if someone creates nice and stable FFI interfaces for rust-lighting, or [wasm loading](https://hacks.mozilla.org/2019/12/using-webassembly-from-dotnet-with-wasmtime/) becomes a thing.

**Comment by knocte** [comment]
geelightning is not really rust-lightning related, just rust-related (but the struggles to bind it from F# still apply). But yeah, if you decide to switch DNL to be just a binding to rust-lightning, we might reconsider our options; we didn't set anything in stone yet though. Another good reading from a very senior developer trying to integrate .NET from Rust: https://ericsink.com/entries/dotnet_rust.html

**Comment by joemphilips** [comment]
> geelightning is not really rust-lightning related, just rust-related 

whoops I thought it is a fork of rust-lightning since the directory structure was the same.

**Comment by joemphilips** [comment]
I'm resuming this, by following the practice in [rust-csharp-ffi](https://github.com/KodrAus/rust-csharp-ffi), I think I can manage to create the FFI. It may take me some time but I want to dig in much deeper before giving it up.

**Comment by joemphilips** [comment]
For someone interested, the PR is [over here](https://github.com/rust-bitcoin/rust-lightning/pull/569)

And the code for C# wrapper is [over here](https://github.com/joemphilips/NRustLightning).

**Comment by knocte** [comment]
> And the code for C# wrapper is over here.

So we can close this issue?

**Comment by joemphilips** [comment]
Yeah why not. I use DNL internally in my binding project. But I suppose we should keep it separated.
