### ISSUE TITLE
Stop supporting Infrastructure.

### ISSUE THREAD

**Issue by joemphilips** [joemphilips/DotNetLightning#98]
I think I will stop running infrastructure tests in CI. It is too dirty that I might re-write everything from scratch while debugging its flaky behavior.

Recently, I’ve been spending most of my efforts on [NRustLightning](https://github.com/joemphilips/NRustLightning), and if this works fine (it probably does.) I don’t need DotNetLightning.Infastructure anymore.
And @knocte and @canndrew are not planning to use it either. So there is no reason to maintain it anymore.

**Comment by knocte** [comment]
> Recently, I’ve been spending most of my efforts on NRustLightning, and if this works fine (it probably does.) I don’t need DotNetLightning.Infastructure anymore.
And @knocte and @canndrew are not planning to use it either. So there is no reason to maintain it anymore.

By the same reasoning above, do you agree to nuke the non-BouncyCastle build?

**Comment by joemphilips** [comment]
By the same reasoning above, do you agree to nuke the non-BouncyCastle build?

Yes.

**Comment by canndrew** [comment]
This sounds fine to me. We're not using the infrastructure stuff at all.
